// Man-Date Seattle Database — All categories
// Last updated: March 26, 2026

export var TEAMS = ["Mariners", "Seahawks", "Sounders", "Kraken", "Storm", "Huskies", "Ballard FC", "Reign"];

export var NEIGHBORHOOD_CLUSTERS = {
  "ballard-fremont": ["Ballard", "Fremont", "Phinney Ridge", "Wallingford", "Green Lake", "Greenwood"],
  "capitol-hill": ["Capitol Hill", "Central District", "First Hill", "Madison"],
  "downtown-belltown": ["Downtown", "Belltown", "Pike Place", "Pioneer Square", "South Lake Union", "Denny Triangle", "Seattle Center", "Queen Anne"],
  "south-seattle": ["Columbia City", "Beacon Hill", "Rainier Valley", "Georgetown", "SoDo", "Hillman City", "Rainier Beach", "Mount Baker"],
  "west-seattle": ["West Seattle", "Alki", "White Center"],
  "north-seattle": ["University District", "Laurelhurst", "Ravenna", "Lake City", "Northgate", "Wedgwood", "Sand Point"],
  "eastside": ["Bellevue", "Kirkland", "Redmond", "Woodinville", "Issaquah", "Bothell", "Kenmore"],
  "waterfront-magnolia": ["Downtown Waterfront", "Interbay", "Magnolia", "Broadview"],
  "madrona-leschi": ["Madrona", "Leschi", "Eastlake"],
};

export var SEASONAL_CONFIG = {
  1:  { season: "winter", suppress: ["water"], boost: ["stayin", "indoor"], note: "Peak cozy season." },
  2:  { season: "winter", suppress: ["water"], boost: ["stayin", "indoor"], note: "Still dark and wet." },
  3:  { season: "spring", suppress: [], boost: ["outdoor"], note: "Cherry blossoms! Bring a jacket." },
  4:  { season: "spring", suppress: [], boost: ["outdoor"], note: "Tulip festival. Trails are green." },
  5:  { season: "spring", suppress: [], boost: ["outdoor", "water"], note: "Good weather switch flips." },
  6:  { season: "summer", suppress: [], boost: ["outdoor", "water", "picnic"], note: "Peak Seattle. Do everything outside." },
  7:  { season: "summer", suppress: [], boost: ["outdoor", "water", "picnic"], note: "Best month. Sunset at 9pm." },
  8:  { season: "summer", suppress: [], boost: ["outdoor", "water", "picnic"], note: "Berry picking, lake swimming." },
  9:  { season: "fall", suppress: [], boost: ["outdoor", "food"], note: "Best hiking month. Clear skies." },
  10: { season: "fall", suppress: ["water"], boost: ["outdoor", "food"], note: "Apple picking, pumpkin patches." },
  11: { season: "winter", suppress: ["water"], boost: ["stayin", "food"], note: "Rain returns. Holiday lights start." },
  12: { season: "winter", suppress: ["water"], boost: ["stayin"], note: "Leavenworth lights, zoo lanterns." },
};

export var BUDGET_GUIDE = {
  drinks: { low: 15, mid: 30, high: 50 },
  food: { low: 15, mid: 35, high: 80 },
  activity: { low: 15, mid: 35, high: 65 },
  event: { low: 30, mid: 65, high: 150 },
  sports: { low: 25, mid: 60, high: 150 },
  outdoor: { low: 0, mid: 10, high: 25 },
  stayin: { low: 0, mid: 15, high: 40 },
  water: { low: 20, mid: 40, high: 85 },
  picnic: { low: 10, mid: 25, high: 45 },
};

export var DB = {
  bars: [
    { name: "Canon", neighborhood: "Capitol Hill", vibe: "upscale", desc: "Whiskey cathedral with 4,000+ bottles. Order an off-menu cocktail and feel like a gentleman.", kidFriendly: false },
    { name: "Navy Strength", neighborhood: "Belltown", vibe: "craft", desc: "Tiki-adjacent cocktail bar. The bartender remembers your order after one visit.", kidFriendly: false },
    { name: "Bathtub Gin & Co.", neighborhood: "Belltown", vibe: "speakeasy", desc: "Hidden speakeasy behind an unmarked door. You'll feel cool just finding it.", kidFriendly: false },
    { name: "Optimism Brewing", neighborhood: "Capitol Hill", vibe: "casual", desc: "Giant indoor space, food trucks rotate, bring your own snacks. Dad paradise.", kidFriendly: true },
    { name: "Stoup Brewing", neighborhood: "Ballard", vibe: "casual", desc: "Ballard's chill brewery with a huge patio and rotating food trucks.", kidFriendly: true },
    { name: "Holy Mountain Brewing", neighborhood: "Interbay", vibe: "craft", desc: "Some of the best beer in Seattle. Grab a crowler.", kidFriendly: false },
    { name: "Flatstick Pub", neighborhood: "Pioneer Square", vibe: "active", desc: "Mini golf + craft beer + Duffin. Competitive dads, unite.", kidFriendly: false },
    { name: "Rhein Haus", neighborhood: "Capitol Hill", vibe: "active", desc: "Indoor bocce courts, giant pretzels, German beer.", kidFriendly: false },
    { name: "Fremont Brewing", neighborhood: "Fremont", vibe: "casual", desc: "Urban beer garden with great IPAs and a block party vibe.", kidFriendly: true },
    { name: "Roquette", neighborhood: "Belltown", vibe: "upscale", desc: "French-inspired cocktails in an Art Deco gem. James Beard-nominated.", kidFriendly: false },
    { name: "Majnoon", neighborhood: "Queen Anne", vibe: "speakeasy", desc: "Persian-inspired cocktails. Sexy date night energy.", kidFriendly: false },
    { name: "Rob Roy", neighborhood: "Capitol Hill", vibe: "upscale", desc: "Dark, lounge-y, legendary cocktails. Try the Gunpowder Punch.", kidFriendly: false },
    { name: "Triangle Spirits", neighborhood: "Fremont", vibe: "craft", desc: "Late-night cocktails plus some of the best fried chicken in Seattle.", kidFriendly: false },
    { name: "Percy's & Co.", neighborhood: "Ballard", vibe: "craft", desc: "Creative cocktails that make you linger for hours.", kidFriendly: false },
    { name: "Death & Co", neighborhood: "Pioneer Square", vibe: "craft", desc: "NYC cocktail legends in Pioneer Square. 24+ original cocktails.", kidFriendly: false },
    { name: "Daphnes", neighborhood: "Edmonds", vibe: "craft", desc: "Tiny 15-seat bar with more energy than places twice its size.", kidFriendly: false },
    { name: "Dark Room", neighborhood: "Greenwood", vibe: "craft", desc: "Korean snacks meet booze-forward cocktails. Kimchi pimento cheese.", kidFriendly: false },
    { name: "Left Bank", neighborhood: "South Park", vibe: "casual", desc: "Best natural wine in Seattle. Bring a burger from Loretta's next door.", kidFriendly: false },
    { name: "Bottlehouse", neighborhood: "Madrona", vibe: "casual", desc: "Chill wine bar with a patio. Great cheesemonger.", kidFriendly: false },
  ],
  restaurants: [
    { name: "Canlis", neighborhood: "Queen Anne", vibe: "fine dining", desc: "The Seattle fine dining experience. Jacket encouraged.", kidFriendly: false, price: "$$$$" },
    { name: "Westward", neighborhood: "South Lake Union", vibe: "upscale casual", desc: "Waterfront seafood with fire pits on the patio. The sunset date spot.", kidFriendly: false, price: "$$$" },
    { name: "Jeffry's", neighborhood: "Capitol Hill", vibe: "upscale casual", desc: "Bateau reborn. Dry-aged steaks with a Humble Cuts program.", kidFriendly: false, price: "$$$" },
    { name: "Communion", neighborhood: "Central District", vibe: "upscale casual", desc: "Southern-meets-PNW comfort food. Mac and cheese is mandatory.", kidFriendly: true, price: "$$$" },
    { name: "Eden Hill", neighborhood: "Queen Anne", vibe: "intimate", desc: "12-seat counter. Chef's tasting. Ultimate date night flex.", kidFriendly: false, price: "$$$$" },
    { name: "Red Mill Burgers", neighborhood: "Phinney Ridge", vibe: "casual", desc: "Legendary Seattle burgers. Cash only.", kidFriendly: true, price: "$" },
    { name: "Un Bien", neighborhood: "Ballard", vibe: "casual", desc: "Caribbean sandwiches that ruin all other sandwiches.", kidFriendly: true, price: "$" },
    { name: "Archipelago", neighborhood: "Hillman City", vibe: "trendy", desc: "Filipino fusion on every best-of list. Book ahead.", kidFriendly: true, price: "$$$" },
    { name: "Sawyer", neighborhood: "Ballard", vibe: "upscale casual", desc: "Seasonal PNW cooking. The Ballard date night spot.", kidFriendly: false, price: "$$$" },
    { name: "Mamnoon", neighborhood: "Capitol Hill", vibe: "upscale casual", desc: "Middle Eastern small plates that make sharing fun.", kidFriendly: true, price: "$$$" },
    { name: "Homer", neighborhood: "Beacon Hill", vibe: "upscale casual", desc: "Mediterranean flavors, wood-fired pitas, lamb ribs.", kidFriendly: true, price: "$$$" },
    { name: "Bar del Corso", neighborhood: "Beacon Hill", vibe: "casual", desc: "Neapolitan pizza institution. NYT top 25.", kidFriendly: true, price: "$$" },
    { name: "Hamsa", neighborhood: "Wallingford", vibe: "casual", desc: "Palestinian counter with incredible sandwiches.", kidFriendly: true, price: "$" },
    { name: "Roma Roma", neighborhood: "Capitol Hill", vibe: "trendy", desc: "Roman-style pizza by weight. Seasonal toppings.", kidFriendly: true, price: "$$" },
    { name: "De La Soil", neighborhood: "Kenmore", vibe: "upscale casual", desc: "Farm-to-table at Copperworks Distilling. Killer kids menu.", kidFriendly: true, price: "$$$" },
    { name: "Mangosteen's Chicken Shop", neighborhood: "Rainier Valley", vibe: "casual", desc: "Fish sauce wings with calamansi. Garlic noodles.", kidFriendly: true, price: "$" },
    { name: "The Corson Building", neighborhood: "Georgetown", vibe: "fine dining", desc: "Lantern-lit garden dinners. Hyper-seasonal PNW. Pure romance.", kidFriendly: false, price: "$$$$" },
    { name: "Meesha", neighborhood: "Capitol Hill", vibe: "upscale", desc: "Creative Indian fine dining. Mutton kheema pao.", kidFriendly: false, price: "$$$" },
    { name: "Tacos Cometa", neighborhood: "Capitol Hill", vibe: "casual", desc: "Cal Anderson taco stand turned restaurant. Open til 2am weekends.", kidFriendly: true, price: "$" },
    { name: "Moto Pizza", neighborhood: "Pioneer Square", vibe: "casual", desc: "Detroit-style pizza with Filipino twists in Smith Tower.", kidFriendly: true, price: "$$" },
    { name: "Blue Willow", neighborhood: "Capitol Hill", vibe: "trendy", desc: "Sichuan ribs, honey walnut prawn buns, lanterns. Date night.", kidFriendly: false, price: "$$" },
    { name: "A.K. Pizza", neighborhood: "Othello", vibe: "casual", desc: "Best pizza in Seattle per everyone. Preorder slots drop at noon.", kidFriendly: true, price: "$$" },
    { name: "Cafe Lolo", neighborhood: "Capitol Hill", vibe: "trendy", desc: "Grain-milling pasta. Very I-know-things-about-food energy.", kidFriendly: false, price: "$$$" },
  ],
  activities: [
    { name: "Bad Axe Throwing", neighborhood: "SoDo", desc: "Throw sharp things at wood. Primal, satisfying.", kidFriendly: false, type: "active" },
    { name: "The Garage", neighborhood: "Capitol Hill", desc: "Bowling + billiards + drinks. Triple threat.", kidFriendly: false, type: "active" },
    { name: "Escape Artist", neighborhood: "Ballard", desc: "Escape rooms that actually make you think.", kidFriendly: true, type: "puzzle" },
    { name: "TopGolf", neighborhood: "Renton", desc: "Driving range meets sports bar.", kidFriendly: true, type: "active" },
    { name: "Comedy Underground", neighborhood: "Pioneer Square", desc: "Intimate comedy club underground. Get there early.", kidFriendly: false, type: "show" },
    { name: "SPIN Seattle", neighborhood: "Downtown", desc: "Ping pong bar. Unreasonably fun after two drinks.", kidFriendly: false, type: "active" },
    { name: "iFLY Indoor Skydiving", neighborhood: "Tukwila", desc: "Indoor skydiving. Kids and you will lose your minds.", kidFriendly: true, type: "active" },
    { name: "Mox Boarding House", neighborhood: "Ballard", desc: "Board game cafe with hundreds of games. Family nerd paradise.", kidFriendly: true, type: "games" },
    { name: "Seattle Bouldering Project", neighborhood: "Fremont", desc: "Indoor climbing. Great workout disguised as fun.", kidFriendly: true, type: "active" },
    { name: "West Seattle Bowl", neighborhood: "West Seattle", desc: "Old-school bowling with cosmic bowling nights.", kidFriendly: true, type: "active" },
    { name: "MoPOP", neighborhood: "Seattle Center", desc: "Museum of Pop Culture. Sci-fi, music, indie games.", kidFriendly: true, type: "explore" },
    { name: "Chihuly Garden and Glass", neighborhood: "Seattle Center", desc: "Mind-blowing glass art. Kids and dates both love it.", kidFriendly: true, type: "explore" },
    { name: "Dining in the Dark", neighborhood: "South Lake Union", desc: "Eat blindfolded. Weird? Yes. Unforgettable? Also yes.", kidFriendly: false, type: "explore" },
    { name: "Jet City Improv", neighborhood: "University District", desc: "Live improv comedy. Consistently hilarious.", kidFriendly: true, type: "show" },
  ],
  familyActivities: [
    { name: "Pacific Science Center", neighborhood: "Seattle Center", desc: "IMAX, butterfly house, laser dome, STEM exhibits. A full day of science disguised as fun.", type: "explore", cost: "$29/$21" },
    { name: "Seattle Aquarium", neighborhood: "Downtown Waterfront", desc: "Sea otters, touch tanks, giant Pacific octopus, new Ocean Pavilion. Kids press their face against every tank.", type: "explore", cost: "$35/$25" },
    { name: "Seattle Children's Museum", neighborhood: "Seattle Center", desc: "Hands-on exhibits and Orca Cove sensory area. Peak toddler entertainment.", type: "explore", cost: "$14" },
    { name: "Museum of Flight", neighborhood: "Georgetown", desc: "Huge, interactive. Sit in real cockpits, watch planes from the tower.", type: "explore", cost: "$29/$21" },
    { name: "MOHAI", neighborhood: "South Lake Union", desc: "Seattle history museum on Lake Union. Free for kids under 14.", type: "explore", cost: "$22/free" },
    { name: "Remlinger Farms", neighborhood: "Carnation", desc: "30 min east. Farm animals, hay rides, mini coaster, pony rides, plus a brewery for dad.", type: "explore", cost: "$17-22" },
    { name: "Artists at Play Playground", neighborhood: "Seattle Center", desc: "Free artist-designed playground with climbing structures and instruments. By the Space Needle.", type: "active", cost: "Free" },
    { name: "Kelsey Creek Farm", neighborhood: "Bellevue", desc: "Free farm with animals, trails, open space. The antidote to screen time.", type: "explore", cost: "Free" },
    { name: "Seattle Children's Theatre", neighborhood: "Seattle Center", desc: "Professional kids shows that adults actually enjoy too.", type: "show", cost: "$25-45" },
    { name: "Funko HQ", neighborhood: "Everett", desc: "Giant Funko world. Star Wars, Disney, Marvel areas. Build-your-own Pop.", type: "explore", cost: "Free entry" },
    { name: "Sky Zone", neighborhood: "Various", desc: "Wall-to-wall trampolines, foam pits, dodgeball courts. Kids bounce until they crash.", type: "active", cost: "$25-35/hr" },
  ],
  water: [
    { name: "Agua Verde Paddle Club", neighborhood: "University District", desc: "Kayak or SUP on Portage Bay, then eat tacos upstairs. Ultimate Seattle combo.", season: "spring-fall", cost: "$20-25/hr" },
    { name: "Northwest Outdoor Center", neighborhood: "Westlake", desc: "Kayak and SUP on Lake Union. Paddle past houseboats and seaplanes.", season: "year-round", cost: "$36/90min" },
    { name: "Moss Bay", neighborhood: "South Lake Union", desc: "Kayaks, SUPs, sailboats on Lake Union. First-come first-paddle. Arrive early on hot days.", season: "may-sept", cost: "$25-30/hr" },
    { name: "Center for Wooden Boats", neighborhood: "South Lake Union", desc: "Classic wooden boats on Lake Union. Free public sailboat rides on Sundays. Seriously.", season: "year-round", cost: "Free-$50/hr" },
    { name: "Ballard Kayak", neighborhood: "Ballard", desc: "Kayak near the Ballard Locks. Great for groups and families. Ages 4+.", season: "april-oct", cost: "$30-45/hr" },
    { name: "Bainbridge Island Ferry", neighborhood: "Downtown Waterfront", desc: "35-min ferry with insane skyline views. Walk-on, get fish and chips on the island, ferry back. $9.45 round trip.", season: "year-round", cost: "$9.45" },
    { name: "Alki Kayak Tours", neighborhood: "West Seattle", desc: "Guided sunset kayak along the Alki coastline. See the skyline from the water.", season: "may-sept", cost: "$65-85" },
    { name: "Green Lake Boat Rentals", neighborhood: "Green Lake", desc: "Paddleboats, kayaks, canoes on Green Lake. Chill afternoon activity for all ages.", season: "may-sept", cost: "$20-30/hr" },
  ],
  picnicCombos: [
    { park: "Gas Works Park", takeout: "Un Bien (Ballard, 15 min)", desc: "Best skyline view + best Caribbean sandwich in Seattle. Fly a kite, live your best dad life.", kidFriendly: true },
    { park: "Golden Gardens", takeout: "Kite Cafe (on-site)", desc: "Beach bonfire + sandwiches and ice cream from the cafe right at the park. Zero detour.", kidFriendly: true },
    { park: "Golden Gardens", takeout: "Senor Moose (Ballard, 5 min)", desc: "Beach bonfire + Mexican takeout. Bring marshmallows for dessert.", kidFriendly: true },
    { park: "Discovery Park", takeout: "Little Chinook's (Fisherman's Terminal, 5 min)", desc: "Lighthouse trail + fish and chips from the source. Tempura salmon, fries on a bench.", kidFriendly: true },
    { park: "Discovery Park", takeout: "Red Mill Burgers (Phinney Ridge, 10 min)", desc: "Lighthouse trail + legendary burgers. Cash only. Hit the ATM first.", kidFriendly: true },
    { park: "Seward Park", takeout: "Archipelago (Hillman City, 5 min)", desc: "Old-growth forest + Filipino takeout. Trails, beach, eagles, lumpia.", kidFriendly: true },
    { park: "Seward Park", takeout: "Bar del Corso pizza (Beacon Hill, 10 min)", desc: "Forest peninsula + Neapolitan pizza that travels well. NYT-approved slices on a blanket.", kidFriendly: true },
    { park: "Green Lake", takeout: "Hamsa (Wallingford, 5 min)", desc: "Walk the loop + Palestinian sandwiches. Kids bike, you eat falafel.", kidFriendly: true },
    { park: "Volunteer Park", takeout: "Tacos Cometa (Cap Hill, 5 min)", desc: "Conservatory stroll, find Bruce Lee's grave, eat carne asada tacos on the lawn.", kidFriendly: true },
    { park: "Volunteer Park", takeout: "Homer to-go (Beacon Hill, 10 min)", desc: "Pita, lamb ragu, roasted chicken. Grab a canned vermouth spritz and soft serve.", kidFriendly: true },
    { park: "Magnuson Park", takeout: "Agua Verde (University District, 5 min)", desc: "Huge lakeside park + fish tacos and canned prickly pear margaritas.", kidFriendly: true },
    { park: "Jefferson Park", takeout: "Bar del Corso pizza (Beacon Hill, 3 min)", desc: "Underrated park with skaters and lawn bowling + Margherita pie from 3 min away.", kidFriendly: true },
    { park: "Carkeek Park", takeout: "Ezell's Famous Chicken (Greenwood, 10 min)", desc: "Forest trails to the beach, train bridge views + fried chicken that is even better at room temp.", kidFriendly: true },
    { park: "Alki Beach", takeout: "Marination Ma Kai (Alki, on-site)", desc: "Take the water taxi from downtown + Hawaiian-Korean tacos at the ferry dock. No car needed.", kidFriendly: true },
    { park: "Olympic Sculpture Park", takeout: "Biscuit Bitch (Downtown, 10 min)", desc: "Free outdoor art walk + unapologetic comfort food. Grab coffee too.", kidFriendly: true },
    { park: "Kerry Park", takeout: "Mamnoon Street (Cap Hill, 10 min)", desc: "THE postcard view + Middle Eastern wraps. Eat with the mountains behind you.", kidFriendly: true },
    { park: "Washington Park Arboretum", takeout: "Sam Choy's Poke (various)", desc: "230 acres of trails + cold poke bowls on a hot day. Salmon over ahi, add spam musubi.", kidFriendly: true },
    { park: "Kubota Garden", takeout: "Mangosteen's (Rainier Valley, 5 min)", desc: "Peaceful Japanese garden + fish sauce wings. Zen before, heat after.", kidFriendly: true },
    { park: "Ballard Locks", takeout: "Un Bien (Ballard, 5 min)", desc: "Watch boats and salmon at the fish ladder + Caribbean sandwich. Summer concerts in the botanical garden.", kidFriendly: true },
    { park: "Ella Bailey Park", takeout: "DeLaurenti (Pike Place, 15 min)", desc: "Hidden gem park with skyline and Rainier views + Italian charcuterie from Pike Place.", kidFriendly: true },
  ],
  hikeCombos: [
    { hike: "Rattlesnake Ledge", brewery: "Snoqualmie Brewery", desc: "4 miles round trip with massive lake views, then a post-hike pint. The classic.", kidFriendly: true, difficulty: "moderate" },
    { hike: "Tiger Mountain", brewery: "Issaquah Brewhouse", desc: "Forested loop with old-growth cedar. Not too steep. Beer in Issaquah after.", kidFriendly: true, difficulty: "moderate" },
    { hike: "Discovery Park Loop", brewery: "Magnolia Village Pub", desc: "Lighthouse trail, 2.8 miles, ends at the beach. No car needed.", kidFriendly: true, difficulty: "easy" },
    { hike: "Carkeek Park", brewery: "Stoup Brewing (Ballard, 15 min)", desc: "Forest trails to the beach, train bridge. Kids love the trains. Stoup after.", kidFriendly: true, difficulty: "easy" },
    { hike: "Twin Falls", brewery: "Volition Brewing (North Bend)", desc: "150-foot falls. Short enough that the kids won't revolt. Beer in North Bend.", kidFriendly: true, difficulty: "easy" },
    { hike: "Franklin Falls", brewery: "Dru Bru (Snoqualmie Pass)", desc: "Walk to a 70-foot waterfall in 1 mile. Then beer at an alpine brewpub at 3,000 feet.", kidFriendly: true, difficulty: "easy" },
    { hike: "Burke-Gilman Trail", brewery: "Woodinville wineries", desc: "Bike 15 miles to wine country. Chateau Ste. Michelle, Redhook, 100+ tasting rooms.", kidFriendly: false, difficulty: "moderate" },
  ],
  outdoor: [
    { name: "Discovery Park", neighborhood: "Magnolia", desc: "534 acres ending at a lighthouse on the beach.", kidFriendly: true },
    { name: "Golden Gardens", neighborhood: "Ballard", desc: "Beach bonfires at sunset. Bring marshmallows.", kidFriendly: true },
    { name: "Gas Works Park", neighborhood: "Wallingford", desc: "Best skyline view + kite flying + picnic potential.", kidFriendly: true },
    { name: "Kerry Park", neighborhood: "Queen Anne", desc: "THE postcard view of Seattle.", kidFriendly: true },
    { name: "Alki Beach", neighborhood: "West Seattle", desc: "Beach walk, fish and chips, skyline views.", kidFriendly: true },
    { name: "Woodland Park Zoo", neighborhood: "Phinney Ridge", desc: "Classic family outing. Penguin exhibit is worth the trip.", kidFriendly: true },
    { name: "Green Lake Loop", neighborhood: "Green Lake", desc: "2.8 mile loop. Walk, bike, or rollerblade.", kidFriendly: true },
    { name: "Rattlesnake Ledge", neighborhood: "North Bend", desc: "Short hike, massive view payoff.", kidFriendly: true },
    { name: "Kubota Garden", neighborhood: "Rainier Beach", desc: "Hidden Japanese garden. Peaceful, beautiful, free.", kidFriendly: true },
    { name: "Seward Park", neighborhood: "Columbia City", desc: "Old-growth forest peninsula on Lake Washington.", kidFriendly: true },
    { name: "Snoqualmie Falls", neighborhood: "Snoqualmie", desc: "Giant waterfall, 45 min drive.", kidFriendly: true },
    { name: "Carkeek Park", neighborhood: "Broadview", desc: "Forest trails to the beach. Kids love the train bridge.", kidFriendly: true },
    { name: "Washington Park Arboretum", neighborhood: "Madison", desc: "230 acres, 5,500 plants, gorgeous walking trails.", kidFriendly: true },
    { name: "Magnuson Park", neighborhood: "Sand Point", desc: "Huge lakeside park. Kite hill, off-leash dog area, art walk.", kidFriendly: true },
  ],
  stayIn: [
    { name: "Board Game Night", items: ["Ticket to Ride", "Raccoon Tycoon", "Dragomino", "Codenames", "Catan", "Azul", "Wingspan", "Sushi Go"], desc: "Pull out the good games. No screens allowed." },
    { name: "Puzzle Night", items: ["1000-piece landscape", "3D puzzle", "Mystery jigsaw"], desc: "Playlist on, drinks poured, 1000 pieces of zen." },
    { name: "Movie Marathon", items: ["80s action classics", "Studio Ghibli night", "Marvel chronological", "Dads pick finally"], desc: "Projector or blanket fort. Your call." },
    { name: "Pizza Cook-Off", items: ["Homemade pizza night", "Taco bar", "Sushi rolling", "Breakfast for dinner"], desc: "Everyone gets a station. Chaos is the ingredient." },
    { name: "Science Experiments", items: ["Mentos and Coke", "Baking soda volcano", "Slime lab", "Crystal growing"], desc: "Be the cool parent. Secretly educational." },
    { name: "Video Game Tournament", items: ["Mario Kart bracket", "Smash Bros tournament", "Minecraft build battle"], desc: "Set up the bracket. Loser does dishes." },
    { name: "Backyard Campout", items: ["Tent setup", "S'mores station", "Ghost stories", "Stargazing app"], desc: "All the camping vibes, zero drive time." },
    { name: "Craft Night", items: ["Tie-dye shirts", "Model kits", "Paint night", "Lego challenge"], desc: "Get messy. Make something. Hang it on the fridge." },
  ],
};
