// Man-Date Seattle Database — All categories
// Last updated: March 27, 2026

export var TEAMS = ["Mariners", "Seahawks", "Sounders", "Kraken", "Storm", "Huskies", "Ballard FC", "Reign", "OL Reign", "UW"];

export var NEIGHBORHOOD_CLUSTERS = {
  "ballard-fremont": ["Ballard", "Fremont", "Phinney Ridge", "Wallingford", "Green Lake", "Greenwood"],
  "capitol-hill": ["Capitol Hill", "Central District", "First Hill", "Madison"],
  "downtown-belltown": ["Downtown", "Belltown", "Pike Place", "Pioneer Square", "South Lake Union", "Denny Triangle", "Seattle Center", "Queen Anne"],
  "south-seattle": ["Columbia City", "Beacon Hill", "Rainier Valley", "Georgetown", "SoDo", "Hillman City", "Rainier Beach", "Mount Baker", "South Park", "Othello"],
  "west-seattle": ["West Seattle", "Alki", "White Center"],
  "north-seattle": ["University District", "Laurelhurst", "Ravenna", "Lake City", "Northgate", "Wedgwood", "Sand Point"],
  "eastside": ["Bellevue", "Kirkland", "Redmond", "Woodinville", "Issaquah", "Bothell", "Kenmore"],
  "waterfront-magnolia": ["Downtown Waterfront", "Interbay", "Magnolia", "Broadview"],
  "madrona-leschi": ["Madrona", "Leschi", "Eastlake"],
  "foothills": ["North Bend", "Snoqualmie", "Issaquah", "Snoqualmie Pass", "Fall City"],
};

export var SEASONAL_CONFIG = {
  1:  { season: "winter", suppress: ["water"], boost: ["stayin", "food", "activity"], note: "Peak cozy season." },
  2:  { season: "winter", suppress: ["water"], boost: ["stayin", "food", "activity"], note: "Still dark and wet." },
  3:  { season: "spring", suppress: [], boost: ["outdoor"], note: "Cherry blossoms! Bring a jacket." },
  4:  { season: "spring", suppress: [], boost: ["outdoor"], note: "Tulip festival. Trails are green." },
  5:  { season: "spring", suppress: [], boost: ["outdoor", "water"], note: "Good weather switch flips." },
  6:  { season: "summer", suppress: [], boost: ["outdoor", "water", "picnic"], note: "Peak Seattle. Do everything outside." },
  7:  { season: "summer", suppress: [], boost: ["outdoor", "water", "picnic"], note: "Best month. Sunset at 9pm." },
  8:  { season: "summer", suppress: [], boost: ["outdoor", "water", "picnic"], note: "Berry picking, lake swimming." },
  9:  { season: "fall", suppress: [], boost: ["outdoor", "food"], note: "Best hiking month. Clear skies." },
  10: { season: "fall", suppress: ["water"], boost: ["outdoor", "food"], note: "Apple picking, pumpkin patches." },
  11: { season: "winter", suppress: ["water"], boost: ["stayin", "food", "event"], note: "Rain returns. Holiday lights start." },
  12: { season: "winter", suppress: ["water"], boost: ["stayin"], note: "Leavenworth lights, zoo lanterns." },
};

export var BUDGET_GUIDE = {
  drinks: { low: 15, mid: 30, high: 50 },
  food: { low: 15, mid: 35, high: 80 },
  activity: { low: 15, mid: 35, high: 65 },
  event: { low: 30, mid: 65, high: 150 },
  concert: { low: 30, mid: 65, high: 150 },
  liveshow: { low: 25, mid: 60, high: 150 },
  show: { low: 25, mid: 50, high: 100 },
  sports: { low: 25, mid: 60, high: 150 },
  outdoor: { low: 0, mid: 10, high: 25 },
  stayin: { low: 0, mid: 15, high: 40 },
  water: { low: 20, mid: 40, high: 85 },
  picnic: { low: 10, mid: 25, high: 45 },
  movie: { low: 12, mid: 18, high: 35 },
};

export var DB = {
  bars: [
    // === COCKTAIL BARS ===
    { name: "Canon", neighborhood: "Capitol Hill", vibe: "upscale", desc: "Whiskey cathedral with 4,000+ bottles. Order an off-menu cocktail and feel like a gentleman.", kidFriendly: false },
    { name: "Navy Strength", neighborhood: "Belltown", vibe: "craft", desc: "Tiki-adjacent cocktail bar. The bartender remembers your order after one visit.", kidFriendly: false },
    { name: "Bathtub Gin & Co.", neighborhood: "Belltown", vibe: "speakeasy", desc: "Hidden speakeasy behind an unmarked door. You'll feel cool just finding it.", kidFriendly: false },
    { name: "Roquette", neighborhood: "Belltown", vibe: "upscale", desc: "French-inspired cocktails in an Art Deco gem. James Beard-nominated.", kidFriendly: false },
    { name: "Majnoon", neighborhood: "Queen Anne", vibe: "speakeasy", desc: "Persian-inspired cocktails. Sexy date night energy.", kidFriendly: false },
    { name: "Rob Roy", neighborhood: "Belltown", vibe: "upscale", desc: "Dark, lounge-y, legendary cocktails. Try the Gunpowder Punch.", kidFriendly: false },
    { name: "Death & Co", neighborhood: "Pioneer Square", vibe: "craft", desc: "NYC cocktail legends in Pioneer Square. 24+ original cocktails.", kidFriendly: false },
    { name: "Daphnes", neighborhood: "Edmonds", vibe: "craft", desc: "Tiny 15-seat bar with more energy than places twice its size.", kidFriendly: false },
    { name: "Dark Room", neighborhood: "Greenwood", vibe: "craft", desc: "Korean snacks meet booze-forward cocktails. Kimchi pimento cheese.", kidFriendly: false },
    { name: "Triangle Spirits", neighborhood: "Fremont", vibe: "craft", desc: "Late-night cocktails plus some of the best fried chicken in Seattle.", kidFriendly: false },
    { name: "Percy's & Co.", neighborhood: "Ballard", vibe: "craft", desc: "Creative cocktails that make you linger for hours.", kidFriendly: false },
    { name: "Bar Miriam", neighborhood: "Queen Anne", vibe: "craft", desc: "Tiny, moody bar with Middle Eastern-inspired cocktails that punch above their weight.", kidFriendly: false },
    { name: "Liberty Bar", neighborhood: "Capitol Hill", vibe: "casual", desc: "Unpretentious Cap Hill standby. Great happy hour and a patio that feels like a secret.", kidFriendly: false },
    { name: "Hazlewood", neighborhood: "Ballard", vibe: "craft", desc: "The bar chefs go to after their shift. Strong drinks, lively vibe, zero pretension.", kidFriendly: false },
    { name: "Phocific Standard Time", neighborhood: "Denny Triangle", vibe: "craft", desc: "Vietnamese-inspired cocktails above Pho Bac. Pandan, fish sauce, egg coffee — sounds weird, tastes incredible.", kidFriendly: false },
    { name: "Bar Sabine", neighborhood: "Fremont", vibe: "craft", desc: "Warm neighborhood cocktail bar with a French-Creole soul and killer snacks.", kidFriendly: false },
    { name: "Inside Passage", neighborhood: "Capitol Hill", vibe: "speakeasy", desc: "Shipwreck-themed tiki speakeasy. Two-hour wait but worth it for the octopus ceiling and rum drinks.", kidFriendly: false },
    { name: "Bar Rumba", neighborhood: "Capitol Hill", vibe: "craft", desc: "Rum-focused bar with Latin vibes. Daiquiris done right.", kidFriendly: false },
    { name: "Zig Zag Cafe", neighborhood: "Pike Place", vibe: "upscale", desc: "Hidden below Pike Place. Birthplace of the Last Word cocktail. A Seattle institution.", kidFriendly: false },
    { name: "Smith Tower Observatory Bar", neighborhood: "Pioneer Square", vibe: "upscale", desc: "Cocktails 35 stories up in Seattle's OG skyscraper. Best view you can drink in front of.", kidFriendly: false },
    { name: "Bottlehouse", neighborhood: "Madrona", vibe: "casual", desc: "Chill wine bar with a patio and great cheesemonger. Madrona's living room.", kidFriendly: false },
    { name: "The Nest", neighborhood: "Downtown", vibe: "upscale", desc: "Rooftop bar atop Thompson Hotel. Skyline views, Elliott Bay sunsets, craft cocktails.", kidFriendly: false },
    { name: "The Mountaineering Club", neighborhood: "Downtown", vibe: "upscale", desc: "Swanky hotel bar with alpine lodge energy. Great for a pre-dinner cocktail.", kidFriendly: false },
    { name: "The Fog Room", neighborhood: "Downtown", vibe: "upscale", desc: "Moody hotel cocktail lounge. Dim lighting, plush seats, very date night.", kidFriendly: false },
    { name: "Firn", neighborhood: "Downtown", vibe: "upscale", desc: "Rooftop bar that is peak summer date night. Views, vibes, and well-made drinks.", kidFriendly: false },
    { name: "Frolik", neighborhood: "Downtown", vibe: "upscale", desc: "Rooftop lounge with a retractable roof. Summer sunset cocktails are unbeatable.", kidFriendly: false },
    { name: "Stampede Cocktail Club", neighborhood: "Capitol Hill", vibe: "craft", desc: "Western-themed cocktail den. Whiskey-forward menu and honky-tonk charm.", kidFriendly: false },
    { name: "Founders Club", neighborhood: "Downtown", vibe: "upscale", desc: "Hidden speakeasy behind a bookshelf in the Fairmont Olympic. Rare spirits, wagyu sliders, pure class.", kidFriendly: false },
    { name: "Radiator Whiskey", neighborhood: "Ballard", vibe: "craft", desc: "Whiskey bar with smoked meat and fun drinks. Also has a Pike Place location.", kidFriendly: false },
    { name: "Four Seasons Goldfinch Tavern Bar", neighborhood: "Downtown", vibe: "upscale", desc: "Hotel bar at the Four Seasons overlooking Elliott Bay. Dress up, sip slow.", kidFriendly: false },
    { name: "Left Bank", neighborhood: "South Park", vibe: "casual", desc: "Best natural wine in Seattle. Bring a burger from Loretta's next door.", kidFriendly: false },
    // === BREWERIES & PUBS ===
    { name: "Optimism Brewing", neighborhood: "Capitol Hill", vibe: "casual", desc: "Giant indoor space, food trucks rotate, bring your own snacks. Dad paradise.", kidFriendly: true },
    { name: "Stoup Brewing Ballard", neighborhood: "Ballard", vibe: "casual", desc: "Ballard's chill brewery with a huge patio and rotating food trucks.", kidFriendly: true },
    { name: "Stoup Brewing Capitol Hill", neighborhood: "Capitol Hill", vibe: "casual", desc: "Stoup's second spot with an outdoor playground area. Kids climb, dads drink IPAs. Everyone wins.", kidFriendly: true },
    { name: "Holy Mountain Brewing", neighborhood: "Interbay", vibe: "craft", desc: "Some of the best beer in Seattle. Saisons, sours, barrel-aged magic. Grab a crowler.", kidFriendly: false },
    { name: "Flatstick Pub", neighborhood: "Pioneer Square", vibe: "active", desc: "Mini golf + craft beer + Duffin. Competitive dads, unite.", kidFriendly: false },
    { name: "Rhein Haus", neighborhood: "Capitol Hill", vibe: "active", desc: "Indoor bocce courts, giant pretzels, German beer.", kidFriendly: false },
    { name: "Fremont Brewing", neighborhood: "Fremont", vibe: "casual", desc: "Urban beer garden with great IPAs and a block party vibe.", kidFriendly: true },
    { name: "Cloudburst Brewing", neighborhood: "South Lake Union", vibe: "craft", desc: "Hop-bomb IPAs from a legend. Tiny taproom, huge flavors. Also near Pike Place.", kidFriendly: false },
    { name: "Urban Family Brewing", neighborhood: "Magnolia", vibe: "casual", desc: "Sour and wild ale specialists tucked in Magnolia. Funky beers, chill space.", kidFriendly: true },
    { name: "Obec Brewing", neighborhood: "Ballard", vibe: "craft", desc: "Czech-inspired lagers and European-style beers in Ballard. Refreshingly different.", kidFriendly: false },
    { name: "Barking Dog Alehouse", neighborhood: "Fremont", vibe: "casual", desc: "Family-friendly pub with rotating food trucks and a great tap list. Dogs welcome too.", kidFriendly: true },
    { name: "Old Stove Brewing", neighborhood: "Pike Place", vibe: "casual", desc: "Brewery in Pike Place Market with waterfront views. Tourist-friendly but genuinely good beer.", kidFriendly: true },
    { name: "Reuben's Brews", neighborhood: "Ballard", vibe: "craft", desc: "Award-winning Ballard brewery. The Crikey IPA is a must. Big taproom with food.", kidFriendly: true },
    { name: "Elysian Capitol Hill", neighborhood: "Capitol Hill", vibe: "casual", desc: "The OG Elysian brewpub on Pike. Solid food menu, great people-watching patio.", kidFriendly: true },
    { name: "Georgetown Brewing", neighborhood: "Georgetown", vibe: "craft", desc: "No-frills tasting room in Georgetown. Manny's Pale Ale was born here. Cash only.", kidFriendly: false },
    { name: "Figurehead Brewing", neighborhood: "Magnolia", vibe: "craft", desc: "Neighborhood brewery in Magnolia with rotating styles and a welcoming taproom.", kidFriendly: true },
    { name: "Rooftop Brewing", neighborhood: "Georgetown", vibe: "casual", desc: "Georgetown brewery with a solid patio and laid-back south-end vibes.", kidFriendly: true },
    { name: "Pacific Inn Pub", neighborhood: "Fremont", vibe: "casual", desc: "Legendary dive bar with the best fish and chips in Seattle. Cash only. No frills, all flavor.", kidFriendly: false },
    { name: "Madrona Arms", neighborhood: "Madrona", vibe: "casual", desc: "Cozy neighborhood pub in Madrona. Fireplace, good taps, community hang.", kidFriendly: true },
    { name: "Macleod's Scottish Pub", neighborhood: "Ballard", vibe: "casual", desc: "Proper Scottish pub with whisky flights, meat pies, and fish and chips. Cozy and legit.", kidFriendly: true },
    // === FOOTHILLS BREWERIES ===
    { name: "Dru Bru + Squatch Box", neighborhood: "Snoqualmie Pass", vibe: "casual", desc: "Alpine brewpub at 3,000 feet with American pub fare inside. Post-hike perfection at the pass.", kidFriendly: true },
    { name: "Volition Brewing", neighborhood: "North Bend", vibe: "casual", desc: "Small-batch brewery in downtown North Bend. Solid tap list and chill vibes after any I-90 hike.", kidFriendly: true },
  ],
  restaurants: [
    // === FINE DINING & SPECIAL OCCASION ===
    { name: "Canlis", neighborhood: "Queen Anne", vibe: "fine dining", desc: "The Seattle fine dining experience. Jacket encouraged. Views of Lake Union forever.", kidFriendly: false, price: "$$$$", book: "tock", bookUrl: "https://www.exploretock.com/canlis" },
    { name: "Archipelago", neighborhood: "Hillman City", vibe: "fine dining", desc: "$265 tasting menu. 12 seats. Books months ahead. Filipino-PNW perfection. Special occasion only.", kidFriendly: false, price: "$$$$", book: "tock", bookUrl: "https://www.exploretock.com/archipelago" },
    { name: "The Corson Building", neighborhood: "Georgetown", vibe: "fine dining", desc: "Lantern-lit garden dinners. Hyper-seasonal PNW. Pure romance.", kidFriendly: false, price: "$$$$", book: "tock", bookUrl: "https://www.exploretock.com/thecorsonbuilding" },
    { name: "Kamonegi", neighborhood: "Fremont", vibe: "fine dining", desc: "Handmade soba noodles and tempura. Hard reservation, worth every effort. 8-course tasting available.", kidFriendly: false, price: "$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/kamonegi" },
    { name: "Sushi Kashiba", neighborhood: "Pike Place", vibe: "fine dining", desc: "Shiro Kashiba's omakase in Pike Place. The godfather of Seattle sushi. Book way ahead.", kidFriendly: false, price: "$$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/sushi-kashiba" },
    { name: "Metropolitan Grill", neighborhood: "Downtown", vibe: "fine dining", desc: "Power-lunch steakhouse since 1985. Old-school steak and martini energy.", kidFriendly: false, price: "$$$$", book: "opentable", bookUrl: "https://www.opentable.com/metropolitan-grill" },
    // === UPSCALE DATE NIGHT ===
    { name: "Westward", neighborhood: "South Lake Union", vibe: "upscale casual", desc: "Waterfront seafood with fire pits on the patio. The sunset date spot.", kidFriendly: false, price: "$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/westward" },
    { name: "Jeffry's", neighborhood: "Capitol Hill", vibe: "upscale casual", desc: "Bateau reborn. Dry-aged steaks with a Humble Cuts program.", kidFriendly: false, price: "$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/jeffrys" },
    { name: "Communion", neighborhood: "Central District", vibe: "upscale casual", desc: "Southern-meets-PNW comfort food. Mac and cheese is mandatory.", kidFriendly: true, price: "$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/communion" },
    { name: "Homer", neighborhood: "Beacon Hill", vibe: "upscale casual", desc: "Mediterranean flavors, wood-fired pitas, lamb ribs. Reopened strong after a fire.", kidFriendly: true, price: "$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/homer" },
    { name: "Meesha", neighborhood: "Capitol Hill", vibe: "upscale", desc: "Creative Indian fine dining. Mutton kheema pao.", kidFriendly: false, price: "$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/meesha" },
    { name: "Blue Willow", neighborhood: "Capitol Hill", vibe: "trendy", desc: "Sichuan ribs, honey walnut prawn buns, lanterns. Date night.", kidFriendly: false, price: "$$", book: "resy", bookUrl: "https://resy.com/cities/sea/blue-willow" },
    { name: "Cafe Lolo", neighborhood: "Capitol Hill", vibe: "trendy", desc: "Grain-milling pasta in a historic space with Russian murals. Just opened, already buzzing.", kidFriendly: false, price: "$$$", book: "walkin" },
    { name: "Matt's in the Market", neighborhood: "Pike Place", vibe: "upscale casual", desc: "Intimate Pike Place gem above the market. Seasonal seafood with killer views.", kidFriendly: false, price: "$$$", book: "opentable", bookUrl: "https://www.opentable.com/matts-in-the-market" },
    { name: "The Pink Door", neighborhood: "Pike Place", vibe: "upscale casual", desc: "Hidden Italian behind an unmarked pink door. Trapeze artists and cabaret some nights. Pure magic.", kidFriendly: false, price: "$$$", book: "opentable", bookUrl: "https://www.opentable.com/the-pink-door" },
    { name: "Spinasse", neighborhood: "Capitol Hill", vibe: "upscale", desc: "Piedmontese pasta by candlelight. Best Italian in Seattle, full stop. Book 60 days out.", kidFriendly: false, price: "$$$", book: "opentable", bookUrl: "https://www.opentable.com/r/spinasse-seattle" },
    { name: "Il Nido", neighborhood: "West Seattle", vibe: "upscale", desc: "Italian farmhouse vibes in West Seattle. Handmade pasta, wood-fired everything. Worth the bridge.", kidFriendly: false, price: "$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/il-nido" },
    { name: "Tomo", neighborhood: "White Center", vibe: "upscale casual", desc: "White Center tasting menu that turns simple ingredients into something you'll think about for weeks.", kidFriendly: false, price: "$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/tomo" },
    { name: "Sushi Kappo Tamura", neighborhood: "Eastlake", vibe: "upscale", desc: "Elegant Eastlake sushi. Omakase or a la carte, both are pristine. Sustainable sourcing.", kidFriendly: false, price: "$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/sushi-kappo-tamura" },
    { name: "Vendemmia", neighborhood: "Capitol Hill", vibe: "upscale casual", desc: "Italian wine bar with house-made pasta and small plates. Warm room, great date energy.", kidFriendly: false, price: "$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/vendemmia" },
    { name: "Maripili Tapas Bar", neighborhood: "Capitol Hill", vibe: "upscale casual", desc: "Spanish tapas with Filipino flair. Gin tonics, patatas bravas, and late-night energy.", kidFriendly: false, price: "$$", book: "resy", bookUrl: "https://resy.com/cities/sea/maripili" },
    { name: "The Walrus and the Carpenter", neighborhood: "Ballard", vibe: "upscale casual", desc: "Renee Erickson's oyster bar. No reservations, worth the wait. Order the shaved brussels.", kidFriendly: false, price: "$$$", book: "walkin" },
    { name: "Delancey", neighborhood: "Ballard", vibe: "upscale casual", desc: "Wood-fired pizza in a cozy Ballard room. Seasonal pies, natural wine, chef's kiss.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Red Cow", neighborhood: "Madrona", vibe: "upscale casual", desc: "Neighborhood gem in Madrona. Seasonal menu, excellent cocktails, intimate room.", kidFriendly: false, price: "$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/red-cow" },
    { name: "Lupo", neighborhood: "Georgetown", vibe: "upscale casual", desc: "Italian-inspired with PNW ingredients. Georgetown's date night surprise. Great pasta.", kidFriendly: false, price: "$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/lupo" },
    { name: "Taurus Ox", neighborhood: "Georgetown", vibe: "upscale casual", desc: "East African and PNW mashup in Georgetown. Injera, dry-aged beef, adventurous and fun.", kidFriendly: false, price: "$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/taurus-ox" },
    { name: "Driftwood", neighborhood: "West Seattle", vibe: "upscale casual", desc: "West Seattle bistro with a rotating seasonal menu. Cozy, intimate, neighborhood treasure.", kidFriendly: false, price: "$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/driftwood-kitchen" },
    { name: "Loretta's Northwesterner", neighborhood: "South Park", vibe: "upscale casual", desc: "Modern diner meets Pacific NW comfort food. Smash burgers, fried chicken, natural wine.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "My Friend Derek's", neighborhood: "Wallingford", vibe: "trendy", desc: "Detroit-style pizza with cult following. Pepperoni cups, crispy cheese edges. Worth the hype.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Shomon Kappo Sushi", neighborhood: "Capitol Hill", vibe: "upscale", desc: "Intimate kappo-style sushi with seasonal omakase. Precise, personal, and unforgettable.", kidFriendly: false, price: "$$$", book: "resy", bookUrl: "https://sho-mon.com/" },
    // === MID-RANGE & NEIGHBORHOOD ===
    { name: "De La Soil", neighborhood: "Kenmore", vibe: "upscale casual", desc: "Farm-to-table at Copperworks Distilling. Killer kids menu. Seattle Met best new restaurant.", kidFriendly: true, price: "$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/de-la-soil" },
    { name: "Little Beast", neighborhood: "Ballard", vibe: "upscale casual", desc: "Eater Seattle 2025 Restaurant of the Year. Multiconcept butcher shop meets restaurant. Inventive, must-try.", kidFriendly: false, price: "$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/little-beast" },
    { name: "Atoma", neighborhood: "Wallingford", vibe: "upscale casual", desc: "James Beard Best New Restaurant finalist. Contemporary new American that's quietly stunning.", kidFriendly: false, price: "$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/atoma" },
    { name: "Cafe Juanita", neighborhood: "Kirkland", vibe: "fine dining", desc: "Eastside Italian fine dining. Tasting menus, wagyu, and braised lamb caramelle in a glowing room.", kidFriendly: false, price: "$$$$", book: "opentable", bookUrl: "https://www.opentable.com/r/cafe-juanita-kirkland" },
    { name: "Alebrijes Kitchen", neighborhood: "Greenwood", vibe: "casual", desc: "Best Mexican in Seattle per The Infatuation. Carnitas, queso fundido, and zero pretension.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Altura", neighborhood: "Capitol Hill", vibe: "fine dining", desc: "Italian tasting menus with caviar dreams. Seasonal, elegant, and worth the splurge.", kidFriendly: false, price: "$$$$", book: "resy", bookUrl: "https://resy.com/cities/sea/altura" },
    { name: "Bar del Corso", neighborhood: "Beacon Hill", vibe: "casual", desc: "Neapolitan pizza institution. NYT top 25.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Roma Roma", neighborhood: "Capitol Hill", vibe: "trendy", desc: "Roman-style pizza by weight. Seasonal toppings.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Cornelly Capitol Hill", neighborhood: "Capitol Hill", vibe: "trendy", desc: "Sourdough pizza and handmade pasta from a cult-favorite kitchen. 96-hour fermented dough.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Cornelly Queen Anne", neighborhood: "Queen Anne", vibe: "trendy", desc: "Second location of the beloved pizza and pasta spot. Same magic, different neighborhood.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Windy City Pie", neighborhood: "Phinney Ridge", vibe: "casual", desc: "Deep dish Chicago-style pizza. Thick, cheesy, unapologetic. Order ahead.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Stevie's Famous", neighborhood: "University District", vibe: "casual", desc: "Best NY-style slice in Seattle per the Seattle Times Pizza Smackdown. No argument here.", kidFriendly: true, price: "$", book: "walkin" },
    { name: "Via Tribunali", neighborhood: "Queen Anne", vibe: "casual", desc: "Legit Neapolitan pizza certified by the Italian govt. Yes, really. Multiple locations.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Damn the Weather", neighborhood: "Pioneer Square", vibe: "upscale casual", desc: "Great dinner spot that doubles as a cocktail bar. Burger is legendary. Pioneer Square anchor.", kidFriendly: false, price: "$$", book: "walkin" },
    { name: "Ba Bar", neighborhood: "Capitol Hill", vibe: "casual", desc: "Vietnamese comfort food. Pho, banh mi, rice plates, and cocktails. Always reliable.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Musang", neighborhood: "Beacon Hill", vibe: "upscale casual", desc: "Filipino kamayan feasts and modern plates. Chef Melissa Miranda is a James Beard finalist.", kidFriendly: true, price: "$$", book: "resy", bookUrl: "https://resy.com/cities/sea/musang" },
    { name: "Reckless Noodle", neighborhood: "Columbia City", vibe: "casual", desc: "Thai noodles and curries in Columbia City. Bold flavors, no-frills setting, big portions.", kidFriendly: true, price: "$", book: "walkin" },
    { name: "Milk Drunk", neighborhood: "Capitol Hill", vibe: "casual", desc: "Burgers, ice cream, and good vibes. The double smash burger is dangerously good.", kidFriendly: true, price: "$", book: "walkin" },
    { name: "Familyfriend", neighborhood: "Georgetown", vibe: "casual", desc: "Korean-American comfort food in Georgetown. Fun menu, chill space, friendly as the name suggests.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Bongos", neighborhood: "Capitol Hill", vibe: "casual", desc: "Cuban sandwiches and Caribbean plates. Plantains, black beans, and counter service charm.", kidFriendly: true, price: "$", book: "walkin" },
    { name: "Beast and Cleaver", neighborhood: "Ballard", vibe: "casual", desc: "Butcher shop sandwich counter. The roast beef sandwich is a top-5 Seattle sandwich.", kidFriendly: true, price: "$", book: "walkin" },
    { name: "WoodShop BBQ", neighborhood: "Central District", vibe: "casual", desc: "Texas-style BBQ in the CD. Brisket, ribs, mac and cheese. Come hungry, leave happy.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Outsider BBQ", neighborhood: "Fremont", vibe: "casual", desc: "Smoked meats and craft beer in Fremont. The pulled pork and jalapeño cheddar sausage are elite.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Kin Len Late Night Thai Bites", neighborhood: "Capitol Hill", vibe: "casual", desc: "Late-night Thai street food. Open past midnight. Larb, pad kra pao, and cold Singha.", kidFriendly: false, price: "$", book: "walkin" },
    { name: "Hamdi", neighborhood: "Wallingford", vibe: "casual", desc: "Middle Eastern restaurant with incredible kebabs, hummus platters, and family-style mezze.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Din Tai Fung Downtown", neighborhood: "Downtown", vibe: "casual", desc: "Legendary soup dumplings. XLB perfection. Expect a wait but it moves fast.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Din Tai Fung Bellevue", neighborhood: "Bellevue", vibe: "casual", desc: "Same perfect dumplings, Eastside location. Usually shorter wait than downtown.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Dough Zone Downtown", neighborhood: "Downtown", vibe: "casual", desc: "Pan-fried soup dumplings that shatter when you bite in. Multiple locations, all great.", kidFriendly: true, price: "$", book: "walkin" },
    { name: "Dough Zone Bellevue", neighborhood: "Bellevue", vibe: "casual", desc: "Eastside outpost. Same crispy-bottomed dumplings, dan dan noodles, and bubble tea.", kidFriendly: true, price: "$", book: "walkin" },
    { name: "Ivar's Salmon House", neighborhood: "Fremont", vibe: "casual", desc: "On the water at the north end of Lake Union. Alder-smoked salmon, Native art, stunning views.", kidFriendly: true, price: "$$", book: "opentable", bookUrl: "https://www.opentable.com/ivars-salmon-house" },
    // === BURGERS ===
    { name: "Red Mill Burgers", neighborhood: "Phinney Ridge", vibe: "casual", desc: "Legendary Seattle burgers. Cash only.", kidFriendly: true, price: "$", book: "walkin" },
    { name: "Lil Woody's", neighborhood: "Capitol Hill", vibe: "casual", desc: "Smash burgers, shakes, and Tillamook cheddar. Multiple locations. Always hits.", kidFriendly: true, price: "$", book: "walkin" },
    { name: "Uneeda Burger", neighborhood: "Fremont", vibe: "casual", desc: "Fremont's best burger. Locally sourced beef, hand-cut fries, craft cocktails on tap.", kidFriendly: true, price: "$$", book: "walkin" },
    // === QUICK & CASUAL ===
    { name: "Un Bien", neighborhood: "Ballard", vibe: "casual", desc: "Caribbean sandwiches that ruin all other sandwiches.", kidFriendly: true, price: "$", book: "walkin" },
    { name: "Hamsa", neighborhood: "Wallingford", vibe: "casual", desc: "Palestinian counter with incredible sandwiches.", kidFriendly: true, price: "$", book: "walkin" },
    { name: "Mangosteen's Chicken Shop", neighborhood: "Rainier Valley", vibe: "casual", desc: "Fish sauce wings with calamansi. Garlic noodles.", kidFriendly: true, price: "$", book: "walkin" },
    { name: "Tacos Cometa", neighborhood: "Capitol Hill", vibe: "casual", desc: "Cal Anderson taco stand turned restaurant. Open til 2am weekends.", kidFriendly: true, price: "$", book: "doordash" },
    { name: "Moto Pizza", neighborhood: "Pioneer Square", vibe: "casual", desc: "Detroit-style pizza with Filipino twists in Smith Tower.", kidFriendly: true, price: "$$", book: "doordash" },
    { name: "A.K. Pizza", neighborhood: "Othello", vibe: "casual", desc: "Best pizza in Seattle per everyone. Preorder slots drop at noon.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Rainier Teriyaki", neighborhood: "Rainier Valley", vibe: "casual", desc: "Old-school Seattle teriyaki. Chicken, rice, salad, done. A local institution.", kidFriendly: true, price: "$", book: "walkin" },
    // === FOOTHILLS (Near trailheads) ===
    { name: "South Fork", neighborhood: "North Bend", vibe: "casual", desc: "PNW gastropub right off I-90 Exit 32. Huge beer garden, craft cocktails, and a kids play area. Post-hike HQ.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Rent's Due BBQ", neighborhood: "North Bend", vibe: "casual", desc: "Smoked meats in North Bend. Perfect post-hike fuel. Brisket, pulled pork, all the sides.", kidFriendly: true, price: "$", book: "walkin" },
    { name: "Twede's Cafe", neighborhood: "North Bend", vibe: "casual", desc: "The Twin Peaks diner. Cherry pie and a damn fine cup of coffee. Surreal and fun.", kidFriendly: true, price: "$", book: "walkin" },
    { name: "Volition Brewing Kitchen", neighborhood: "North Bend", vibe: "casual", desc: "Brewery taproom with solid pub food in downtown North Bend. Post-hike pints and pizza.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Montalcino Ristorante", neighborhood: "Issaquah", vibe: "upscale", desc: "Intimate Italian in Olde Town Issaquah. Handmade pasta, great wine, live Italian singer. Date night after Tiger Mountain.", kidFriendly: false, price: "$$$", book: "opentable", bookUrl: "https://www.opentable.com/montalcino-ristorante-italiano" },
    { name: "Black Duck Cask & Bottle", neighborhood: "Issaquah", vibe: "casual", desc: "Pub food, 350+ drinks, pool tables. Solid post-hike hangout in Issaquah.", kidFriendly: true, price: "$$", book: "walkin" },
    { name: "Enzo's Bistro & Bar", neighborhood: "Issaquah", vibe: "upscale casual", desc: "Italian-American in Issaquah. Wood-fired pizza, cocktails, and a great patio. Good for groups.", kidFriendly: true, price: "$$", book: "opentable", bookUrl: "https://www.opentable.com/enzos-bistro-and-bar-issaquah" },
    { name: "Dru Bru + Squatch Box", neighborhood: "Snoqualmie Pass", vibe: "casual", desc: "Alpine brewpub at 3,000 feet with pub fare. The only post-Franklin Falls option. Worth the stop.", kidFriendly: true, price: "$$", book: "walkin" },
  ],
  activities: [
    { name: "Bad Axe Throwing", neighborhood: "SoDo", desc: "Throw sharp things at wood. Primal, satisfying.", kidFriendly: false, type: "active" },
    { name: "The Garage", neighborhood: "Capitol Hill", desc: "Bowling + billiards + drinks. Triple threat.", kidFriendly: false, type: "active" },
    { name: "Escape Artist", neighborhood: "Ballard", desc: "Escape rooms that actually make you think.", kidFriendly: true, type: "puzzle" },
    { name: "TopGolf", neighborhood: "Renton", desc: "Driving range meets sports bar.", kidFriendly: true, type: "active" },
    { name: "Comedy Underground", neighborhood: "Pioneer Square", desc: "Intimate comedy club underground. Get there early.", kidFriendly: false, type: "show" },
    { name: "SPIN Seattle", neighborhood: "Downtown", desc: "Ping pong bar. Unreasonably fun after two drinks.", kidFriendly: false, type: "active" },
    { name: "iFLY Indoor Skydiving", neighborhood: "Tukwila", desc: "Indoor skydiving. Kids and you will lose your minds.", kidFriendly: true, type: "active" },
    { name: "Mox Boarding House", neighborhood: "Ballard", desc: "Board game cafe with hundreds of games. Family nerd paradise.", kidFriendly: true, type: "games" },
    { name: "Seattle Bouldering Project", neighborhood: "Fremont", desc: "Indoor climbing. Great workout disguised as fun.", kidFriendly: true, type: "active" },
    { name: "West Seattle Bowl", neighborhood: "West Seattle", desc: "Old-school bowling with cosmic bowling nights.", kidFriendly: true, type: "active" },
    { name: "MoPOP", neighborhood: "Seattle Center", desc: "Museum of Pop Culture. Sci-fi, music, indie games.", kidFriendly: true, type: "explore" },
    { name: "Chihuly Garden and Glass", neighborhood: "Seattle Center", desc: "Mind-blowing glass art. Kids and dates both love it.", kidFriendly: true, type: "explore" },
    { name: "Dining in the Dark", neighborhood: "South Lake Union", desc: "Eat blindfolded. Weird? Yes. Unforgettable? Also yes.", kidFriendly: false, type: "explore" },
    { name: "Jet City Improv", neighborhood: "University District", desc: "Live improv comedy. Consistently hilarious.", kidFriendly: true, type: "show" },
    // === NEW ACTIVITIES ===
    { name: "Seattle Art Museum", neighborhood: "Downtown", desc: "World-class art downtown. Free first Thursdays. Pairs perfectly with dinner in Pioneer Square.", kidFriendly: true, type: "explore" },
    { name: "Bill Speidel's Underground Tour", neighborhood: "Pioneer Square", desc: "Walk through the underground city beneath Pioneer Square. Weird Seattle history at its best.", kidFriendly: true, type: "explore" },
    { name: "Seattle Great Wheel", neighborhood: "Downtown Waterfront", desc: "175-foot Ferris wheel on the waterfront. Get a private gondola for date night.", kidFriendly: true, type: "explore" },
    { name: "Lucky Strike", neighborhood: "Bellevue", desc: "Upscale bowling, craft cocktails, and lounge vibes. Date night bowling done right.", kidFriendly: false, type: "active" },
    { name: "Pottery Northwest", neighborhood: "South Lake Union", desc: "Take a couples pottery class. Ghost reenactment optional but encouraged.", kidFriendly: false, type: "explore" },
    { name: "The Triple Door", neighborhood: "Downtown", desc: "Dinner theater with live music, comedy, and cabaret. Food is surprisingly good.", kidFriendly: false, type: "show" },
    { name: "AIRE Ancient Baths", neighborhood: "Capitol Hill", desc: "Thermal baths and massage in a candlelit space. Ultimate couples date night relaxation.", kidFriendly: false, type: "explore" },
    { name: "Woodinville Wine Tasting", neighborhood: "Woodinville", desc: "100+ wineries and tasting rooms 30 min from Seattle. Chateau Ste. Michelle, DeLille, and more.", kidFriendly: false, type: "explore" },
    { name: "K1 Speed", neighborhood: "Redmond", desc: "Indoor go-kart racing. Electric karts hit 45 mph. Competitive dads thrive here.", kidFriendly: true, type: "active" },
    { name: "ACT Theatre", neighborhood: "Downtown", desc: "Intimate theater with consistently great shows. Date night with actual culture.", kidFriendly: false, type: "show" },
  ],
  familyActivities: [
    { name: "Pacific Science Center", neighborhood: "Seattle Center", desc: "IMAX, butterfly house, laser dome, STEM exhibits. A full day of science disguised as fun.", type: "explore", cost: "$29/$21" },
    { name: "Seattle Aquarium", neighborhood: "Downtown Waterfront", desc: "Sea otters, touch tanks, giant Pacific octopus, new Ocean Pavilion. Kids press their face against every tank.", type: "explore", cost: "$35/$25" },
    { name: "Seattle Children's Museum", neighborhood: "Seattle Center", desc: "Hands-on exhibits and Orca Cove sensory area. Peak toddler entertainment.", type: "explore", cost: "$14" },
    { name: "Museum of Flight", neighborhood: "Georgetown", desc: "Huge, interactive. Sit in real cockpits, watch planes from the tower.", type: "explore", cost: "$29/$21" },
    { name: "MOHAI", neighborhood: "South Lake Union", desc: "Seattle history museum on Lake Union. Free for kids under 14.", type: "explore", cost: "$22/free" },
    { name: "Remlinger Farms", neighborhood: "Carnation", desc: "30 min east. Farm animals, hay rides, mini coaster, pony rides, plus a brewery for dad.", type: "explore", cost: "$17-22" },
    { name: "Artists at Play Playground", neighborhood: "Seattle Center", desc: "Free artist-designed playground with climbing structures and instruments. By the Space Needle.", type: "active", cost: "Free" },
    { name: "Kelsey Creek Farm", neighborhood: "Bellevue", desc: "Free farm with animals, trails, open space. The antidote to screen time.", type: "explore", cost: "Free" },
    { name: "Seattle Children's Theatre", neighborhood: "Seattle Center", desc: "Professional kids shows that adults actually enjoy too.", type: "show", cost: "$25-45" },
    { name: "Funko HQ", neighborhood: "Everett", desc: "Giant Funko world. Star Wars, Disney, Marvel areas. Build-your-own Pop.", type: "explore", cost: "Free entry" },
    { name: "Sky Zone", neighborhood: "Various", desc: "Wall-to-wall trampolines, foam pits, dodgeball courts. Kids bounce until they crash.", type: "active", cost: "$25-35/hr" },
  ],
  water: [
    { name: "Agua Verde Paddle Club", neighborhood: "University District", desc: "Kayak or SUP on Portage Bay, then eat tacos upstairs. Ultimate Seattle combo.", season: "spring-fall", cost: "$20-25/hr" },
    { name: "Northwest Outdoor Center", neighborhood: "South Lake Union", desc: "Kayak and SUP on Lake Union. Paddle past houseboats and seaplanes.", season: "year-round", cost: "$36/90min" },
    { name: "Moss Bay", neighborhood: "South Lake Union", desc: "Kayaks, SUPs, sailboats on Lake Union. First-come first-paddle. Arrive early on hot days.", season: "may-sept", cost: "$25-30/hr" },
    { name: "Center for Wooden Boats", neighborhood: "South Lake Union", desc: "Classic wooden boats on Lake Union. Free public sailboat rides on Sundays. Seriously.", season: "year-round", cost: "Free-$50/hr" },
    { name: "Ballard Kayak", neighborhood: "Ballard", desc: "Kayak near the Ballard Locks. Great for groups and families. Ages 4+.", season: "april-oct", cost: "$30-45/hr" },
    { name: "Bainbridge Island Ferry", neighborhood: "Downtown Waterfront", desc: "35-min ferry with insane skyline views. Walk-on, get fish and chips on the island, ferry back. $9.45 round trip.", season: "year-round", cost: "$9.45" },
    { name: "Alki Kayak Tours", neighborhood: "West Seattle", desc: "Guided sunset kayak along the Alki coastline. See the skyline from the water.", season: "may-sept", cost: "$65-85" },
    { name: "Green Lake Boat Rentals", neighborhood: "Green Lake", desc: "Paddleboats, kayaks, canoes on Green Lake. Chill afternoon activity for all ages.", season: "may-sept", cost: "$20-30/hr" },
  ],
  picnicCombos: [
    { park: "Gas Works Park", takeout: "Un Bien (Ballard, 15 min)", desc: "Best skyline view + best Caribbean sandwich in Seattle. Fly a kite, live your best dad life.", kidFriendly: true },
    { park: "Golden Gardens", takeout: "Kite Cafe (on-site)", desc: "Beach bonfire + sandwiches and ice cream from the cafe right at the park. Zero detour.", kidFriendly: true },
    { park: "Golden Gardens", takeout: "Senor Moose (Ballard, 5 min)", desc: "Beach bonfire + Mexican takeout. Bring marshmallows for dessert.", kidFriendly: true },
    { park: "Discovery Park", takeout: "Little Chinook's (Fisherman's Terminal, 5 min)", desc: "Lighthouse trail + fish and chips from the source. Tempura salmon, fries on a bench.", kidFriendly: true },
    { park: "Discovery Park", takeout: "Red Mill Burgers (Phinney Ridge, 10 min)", desc: "Lighthouse trail + legendary burgers. Cash only. Hit the ATM first.", kidFriendly: true },
    { park: "Seward Park", takeout: "Homer to-go (Beacon Hill, 10 min)", desc: "Old-growth forest peninsula + pita, lamb ragu, and hummus from Homer. Grab a canned spritz for the walk.", kidFriendly: true },
    { park: "Seward Park", takeout: "Bar del Corso pizza (Beacon Hill, 10 min)", desc: "Forest peninsula + Neapolitan pizza that travels well. NYT-approved slices on a blanket.", kidFriendly: true },
    { park: "Green Lake", takeout: "Hamsa (Wallingford, 5 min)", desc: "Walk the loop + Palestinian sandwiches. Kids bike, you eat falafel.", kidFriendly: true },
    { park: "Volunteer Park", takeout: "Tacos Cometa (Cap Hill, 5 min)", desc: "Conservatory stroll, find Bruce Lee's grave, eat carne asada tacos on the lawn.", kidFriendly: true },
    { park: "Volunteer Park", takeout: "Homer to-go (Beacon Hill, 10 min)", desc: "Pita, lamb ragu, roasted chicken. Grab a canned vermouth spritz and soft serve.", kidFriendly: true },
    { park: "Magnuson Park", takeout: "Agua Verde (University District, 5 min)", desc: "Huge lakeside park + fish tacos and canned prickly pear margaritas.", kidFriendly: true },
    { park: "Jefferson Park", takeout: "Bar del Corso pizza (Beacon Hill, 3 min)", desc: "Underrated park with skaters and lawn bowling + Margherita pie from 3 min away.", kidFriendly: true },
    { park: "Carkeek Park", takeout: "Ezell's Famous Chicken (Greenwood, 10 min)", desc: "Forest trails to the beach, train bridge views + fried chicken that is even better at room temp.", kidFriendly: true },
    { park: "Alki Beach", takeout: "Marination Ma Kai (Alki, on-site)", desc: "Take the water taxi from downtown + Hawaiian-Korean tacos at the ferry dock. No car needed.", kidFriendly: true },
    { park: "Olympic Sculpture Park", takeout: "Biscuit Bitch (Downtown, 10 min)", desc: "Free outdoor art walk + unapologetic comfort food. Grab coffee too.", kidFriendly: true },
    { park: "Kerry Park", takeout: "Cornelly Queen Anne (Queen Anne, 5 min)", desc: "THE postcard view + sourdough pizza slices. Eat with the mountains behind you.", kidFriendly: true },
    { park: "Washington Park Arboretum", takeout: "Sam Choy's Poke (various)", desc: "230 acres of trails + cold poke bowls on a hot day. Salmon over ahi, add spam musubi.", kidFriendly: true },
    { park: "Kubota Garden", takeout: "Mangosteen's (Rainier Valley, 5 min)", desc: "Peaceful Japanese garden + fish sauce wings. Zen before, heat after.", kidFriendly: true },
    { park: "Ballard Locks", takeout: "Un Bien (Ballard, 5 min)", desc: "Watch boats and salmon at the fish ladder + Caribbean sandwich. Summer concerts in the botanical garden.", kidFriendly: true },
    { park: "Ella Bailey Park", takeout: "DeLaurenti (Pike Place, 15 min)", desc: "Hidden gem park with skyline and Rainier views + Italian charcuterie from Pike Place.", kidFriendly: true },
    { park: "Lincoln Park", takeout: "Il Nido to-go (West Seattle, 5 min)", desc: "Forest trails to a saltwater pool + handmade pasta from West Seattle's best Italian.", kidFriendly: true },
    { park: "Meridian Park", takeout: "Uneeda Burger (Fremont, 3 min)", desc: "Hidden Wallingford park + Fremont's best burger and hand-cut fries.", kidFriendly: true },
  ],
  hikeCombos: [
    { hike: "Rattlesnake Ledge", brewery: "Snoqualmie Brewery", desc: "4 miles round trip with massive lake views, then a post-hike pint. The classic.", kidFriendly: true, difficulty: "moderate" },
    { hike: "Tiger Mountain", brewery: "Issaquah Brewhouse", desc: "Forested loop with old-growth cedar. Not too steep. Beer in Issaquah after.", kidFriendly: true, difficulty: "moderate" },
    { hike: "Discovery Park Loop", brewery: "Magnolia Village Pub", desc: "Lighthouse trail, 2.8 miles, ends at the beach. No car needed.", kidFriendly: true, difficulty: "easy" },
    { hike: "Carkeek Park", brewery: "Stoup Brewing (Ballard, 15 min)", desc: "Forest trails to the beach, train bridge. Kids love the trains. Stoup after.", kidFriendly: true, difficulty: "easy" },
    { hike: "Twin Falls", brewery: "Volition Brewing (North Bend)", desc: "150-foot falls. Short enough that the kids won't revolt. Beer in North Bend.", kidFriendly: true, difficulty: "easy" },
    { hike: "Franklin Falls", brewery: "Dru Bru (Snoqualmie Pass)", desc: "Walk to a 70-foot waterfall in 1 mile. Then beer at an alpine brewpub at 3,000 feet.", kidFriendly: true, difficulty: "easy" },
    { hike: "Burke-Gilman Trail", brewery: "Woodinville wineries", desc: "Bike 15 miles to wine country. Chateau Ste. Michelle, Redhook, 100+ tasting rooms.", kidFriendly: false, difficulty: "moderate" },
    { hike: "Poo Poo Point", brewery: "Cloudburst (SLU, 30 min)", desc: "Watch paragliders launch off the ridge. 3.7 miles, solid climb. Reward yourself with a Cloudburst IPA.", kidFriendly: true, difficulty: "moderate" },
    { hike: "Ebey's Landing (Whidbey)", brewery: "Penn Cove Brewing", desc: "Coastal bluff trail with wildflowers and Puget Sound views. Ferry + beer + adventure.", kidFriendly: true, difficulty: "moderate" },
    { hike: "Little Si", brewery: "Volition Brewing (North Bend)", desc: "Great intro hike. 2 miles to a viewpoint. Kids handle it. Beer in North Bend after.", kidFriendly: true, difficulty: "easy" },
    // === CITY WALKS ===
    { hike: "Volunteer Park to Broadway", brewery: "any Capitol Hill bar", desc: "Stroll through Volunteer Park (conservatory, water tower views), then walk down Broadway for food and drinks. Flat and easy.", kidFriendly: true, difficulty: "easy" },
    { hike: "Burke-Gilman: Fremont to Gas Works", brewery: "Fremont Brewing", desc: "2-mile waterfront walk along the ship canal past houseboats to Gas Works Park. Best skyline view. Flat, scenic, pairs with Fremont breweries.", kidFriendly: true, difficulty: "easy" },
  ],
  outdoor: [
    { name: "Discovery Park", neighborhood: "Magnolia", desc: "534 acres ending at a lighthouse on the beach.", kidFriendly: true },
    { name: "Golden Gardens", neighborhood: "Ballard", desc: "Beach bonfires at sunset. Bring marshmallows.", kidFriendly: true },
    { name: "Gas Works Park", neighborhood: "Wallingford", desc: "Best skyline view + kite flying + picnic potential.", kidFriendly: true },
    { name: "Kerry Park", neighborhood: "Queen Anne", desc: "THE postcard view of Seattle.", kidFriendly: true },
    { name: "Alki Beach", neighborhood: "West Seattle", desc: "Beach walk, fish and chips, skyline views.", kidFriendly: true },
    { name: "Woodland Park Zoo", neighborhood: "Phinney Ridge", desc: "Classic family outing. Penguin exhibit is worth the trip.", kidFriendly: true },
    { name: "Green Lake Loop", neighborhood: "Green Lake", desc: "2.8 mile loop. Walk, bike, or rollerblade.", kidFriendly: true },
    { name: "Rattlesnake Ledge", neighborhood: "North Bend", desc: "Short hike, massive view payoff.", kidFriendly: true },
    { name: "Kubota Garden", neighborhood: "Rainier Beach", desc: "Hidden Japanese garden. Peaceful, beautiful, free.", kidFriendly: true },
    { name: "Seward Park", neighborhood: "Columbia City", desc: "Old-growth forest peninsula on Lake Washington.", kidFriendly: true },
    { name: "Snoqualmie Falls", neighborhood: "Snoqualmie", desc: "Giant waterfall, 45 min drive.", kidFriendly: true },
    { name: "Carkeek Park", neighborhood: "Broadview", desc: "Forest trails to the beach. Kids love the train bridge.", kidFriendly: true },
    { name: "Washington Park Arboretum", neighborhood: "Madison", desc: "230 acres, 5,500 plants, gorgeous walking trails.", kidFriendly: true },
    { name: "Magnuson Park", neighborhood: "Sand Point", desc: "Huge lakeside park. Kite hill, off-leash dog area, art walk.", kidFriendly: true },
    { name: "Lincoln Park", neighborhood: "West Seattle", desc: "Forest meets beach. Saltwater pool in summer. Less crowded than Alki.", kidFriendly: true },
    { name: "Volunteer Park", neighborhood: "Capitol Hill", desc: "Conservatory, water tower views, Bruce Lee's grave. A Cap Hill essential.", kidFriendly: true },
  ],
  stayIn: [
    { name: "Board Game Night", items: ["Ticket to Ride", "Raccoon Tycoon", "Dragomino", "Codenames", "Catan", "Azul", "Wingspan", "Sushi Go"], desc: "Pull out the good games. No screens allowed." },
    { name: "Puzzle Night", items: ["1000-piece landscape", "3D puzzle", "Mystery jigsaw"], desc: "Playlist on, drinks poured, 1000 pieces of zen." },
    { name: "Movie Night", items: ["80s action classics", "Studio Ghibli night", "Marvel chronological", "Dads pick finally"], desc: "Projector or blanket fort. Your call." },
    { name: "Pizza Cook-Off", items: ["Homemade pizza night", "Taco bar", "Sushi rolling", "Breakfast for dinner"], desc: "Everyone gets a station. Chaos is the ingredient." },
    { name: "Video Game Tournament", items: ["Mario Kart bracket", "Smash Bros tournament", "Minecraft build battle"], desc: "Set up the bracket. Loser does dishes." },
    { name: "Backyard Campout", items: ["Tent setup", "S'mores station", "Ghost stories", "Stargazing app"], desc: "All the camping vibes, zero drive time." },
  ],
};

// Approved venue whitelist for Ticketmaster filtering
export var VENUE_WHITELIST = {
  sports: [
    { name: "T-Mobile Park", neighborhood: "SoDo" },
    { name: "Lumen Field", neighborhood: "SoDo" },
    { name: "Climate Pledge Arena", neighborhood: "Queen Anne" },
    { name: "Husky Stadium", neighborhood: "University District" },
    { name: "Alaska Airlines Arena", neighborhood: "University District" },
    { name: "Hec Edmundson Pavilion", neighborhood: "University District" },
    { name: "Husky Ballpark", neighborhood: "University District" },
    { name: "Husky Softball Stadium", neighborhood: "University District" },
    { name: "Interbay Stadium", neighborhood: "Interbay" },
  ],
  shows: [
    { name: "The Showbox", neighborhood: "Downtown" },
    { name: "Showbox SoDo", neighborhood: "SoDo" },
    { name: "Neumos", neighborhood: "Capitol Hill" },
    { name: "The Crocodile", neighborhood: "Belltown" },
    { name: "Paramount Theatre", neighborhood: "Downtown" },
    { name: "Moore Theatre", neighborhood: "Belltown" },
    { name: "Neptune Theatre", neighborhood: "University District" },
    { name: "Benaroya Hall", neighborhood: "Downtown" },
    { name: "WAMU Theater", neighborhood: "SoDo" },
    { name: "Chateau Ste. Michelle Winery", neighborhood: "Woodinville" },
    { name: "Remlinger Farms", neighborhood: "Carnation" },
    { name: "Woodland Park Zoo", neighborhood: "Phinney Ridge" },
    { name: "Marymoor Park", neighborhood: "Redmond" },
    { name: "5th Avenue Theatre", neighborhood: "Downtown" },
    { name: "Seattle Rep", neighborhood: "Seattle Center" },
    { name: "ACT Theatre", neighborhood: "Downtown" },
    { name: "Comedy Underground", neighborhood: "Pioneer Square" },
    { name: "Jet City Improv", neighborhood: "University District" },
    { name: "Unexpected Productions", neighborhood: "Pike Place" },
    { name: "McCaw Hall", neighborhood: "Seattle Center" },
    { name: "The Triple Door", neighborhood: "Downtown" },
    { name: "Town Hall Seattle", neighborhood: "First Hill" },
    { name: "Tractor Tavern", neighborhood: "Ballard" },
  ],
};

// Movie theaters for the movie feature
export var THEATERS = [
  // Seattle — Character spots (prioritize for recommendations)
  { name: "Central Cinema", neighborhood: "Central District", vibe: "date", desc: "Eat and drink during the movie. Themed screenings. Peak date night.", kidFriendly: false, fandango: "central-cinema-seattle" },
  { name: "Majestic Bay", neighborhood: "Ballard", desc: "Classic Ballard single-screen. Great neighborhood theater.", kidFriendly: true, fandango: "majestic-bay-theatres-seattle" },
  { name: "SIFF Cinema Egyptian", neighborhood: "Capitol Hill", vibe: "date", desc: "Gorgeous 1915 art deco theater. Indie and festival films.", kidFriendly: true, fandango: "siff-cinema-egyptian-seattle" },
  { name: "SIFF Cinema Uptown", neighborhood: "Queen Anne", desc: "Independent and foreign films near Seattle Center.", kidFriendly: true, fandango: "siff-cinema-uptown-seattle" },
  { name: "Northwest Film Forum", neighborhood: "Capitol Hill", vibe: "date", desc: "Indie essential. Arthouse, rare films, filmmaker Q&As.", kidFriendly: false, fandango: "northwest-film-forum-seattle" },
  { name: "The Beacon", neighborhood: "Columbia City", desc: "Repertory cinema in a neighborhood gem. Classics and cult films.", kidFriendly: true, fandango: "the-beacon-seattle" },
  { name: "Historic Admiral Theater", neighborhood: "West Seattle", desc: "Classic single-screen with neighborhood charm.", kidFriendly: true, fandango: "admiral-theater-seattle" },
  { name: "Ark Lodge Cinemas", neighborhood: "Columbia City", desc: "Neighborhood indie theater. Cozy and unpretentious.", kidFriendly: true, fandango: "ark-lodge-cinemas-seattle" },
  // Seattle — Chains
  { name: "AMC Pacific Place", neighborhood: "Downtown", desc: "Downtown multiplex. All the blockbusters.", kidFriendly: true, fandango: "amc-pacific-place-11-seattle" },
  { name: "Regal Meridian", neighborhood: "Downtown", desc: "Big chain downtown. Recliners.", kidFriendly: true, fandango: "regal-meridian-seattle" },
  { name: "Regal Thornton Place", neighborhood: "Northgate", desc: "North Seattle chain option.", kidFriendly: true, fandango: "regal-thornton-place-seattle" },
  // Seattle — IMAX
  { name: "Boeing IMAX Theater", neighborhood: "Seattle Center", desc: "Six-story IMAX screen at Pacific Science Center.", kidFriendly: true, fandango: "boeing-imax-theater-seattle" },
  { name: "PACCAR IMAX Theater", neighborhood: "Seattle Center", desc: "35-foot IMAX at Pacific Science Center.", kidFriendly: true, fandango: "paccar-imax-theater-seattle" },
  // Bellevue / Eastside — Upscale date night
  { name: "IPIC Redmond", neighborhood: "Redmond", vibe: "date", desc: "21+. Luxury recliners, cocktails and food served during the movie. Elite date night.", kidFriendly: false, fandango: "ipic-theaters-redmond" },
  { name: "Cinemark Reserve Lincoln Square", neighborhood: "Bellevue", vibe: "date", desc: "21+. Leather recliners, bar, upscale Bellevue cinema.", kidFriendly: false, fandango: "cinemark-reserve-bellevue" },
  // Bellevue / Eastside — Standard
  { name: "Cinemark Lincoln Square", neighborhood: "Bellevue", desc: "Big screens, IMAX, free parking at Bellevue Square.", kidFriendly: true, fandango: "cinemark-lincoln-square-cinemas-bellevue" },
  { name: "Regal Crossroads Bellevue", neighborhood: "Bellevue", desc: "Eastside chain option.", kidFriendly: true, fandango: "regal-crossroads-bellevue" },
  { name: "AMC Factoria 8", neighborhood: "Bellevue", desc: "Bellevue recliners, self-serve butter.", kidFriendly: true, fandango: "amc-factoria-8-bellevue" },
];
